### ISSUE TITLE
to_rds() is slow on big datasets

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#106]
The bottleneck seems to be in `to_csv() `or maybe even before that (fetching from Denodo?). I see a few possible improvements:

- [x] **Increase chunk size for reading data from Denodo**

Change the `Chunk size` setting in Denodo ODBC settings to 10,000. This should make QFrame read the data much faster from Denodo (default is 100 because it's not optimized for tabular format databases).

![image](https://user-images.githubusercontent.com/54932987/64715258-6bdd8600-d4c0-11e9-8f54-d3e76f8ffd00.png)

- **Split the data into several files to utilize Redshift's built-in parallelization** 
**EDIT**: We will be parallelizing on our end.

Modify `to_csv()` to split the data into several files (default of 4 should be fine)
If we do above, it's a best practice to generate a [manifest](https://docs.aws.amazon.com/redshift/latest/dg/r_COPY_command_examples.html#copy-command-examples-manifest) to specify files to upload and add it to the `COPY` statement

- [ ] **Compress data**

Use `compression="gzip"` parameter in `pandas.to_csv()`. This requires a modification of the `COPY` statement like so:

```
copy customer from 's3://mybucket/customer.lzo' 
iam_role 'arn:aws:iam::0123456789012:role/MyRedshiftRole'
delimiter '|' gzip;
```

**Comment by michalz92** [comment]
As a reference, today on a VM it took 4 hours to generate a 800MB csv (for backlog process). Even considering that both Denodo and VM are a bit slow, I think it shouldn't take more than an hour to fetch this data from Denodo and write to disk.

**Comment by malinaa96** [comment]
I think it takes so much time because of Denodo. I did some testing on artificial database and with around 5-6 mln rows (801 MB csv size) it took me 2 minutes to load the data 
![image](https://user-images.githubusercontent.com/52569986/64760924-24e0a680-d53b-11e9-8935-fc242884472b.png)

But as you see loading data to csv takes more time than fetching the data. I'm not sure thought if changing the size of chunk would change anything about the speed. As you see in my case it didn't change much. We are spliting the data to chunks to reduce memory usage.

The idea with parallel loading sounds good but then we have to think how to split the data. In `to_csv` function I'm using a [cursor](http://initd.org/psycopg/docs/cursor.html). He is adding an index to each row. If the chunksize is eg 1k then inside a loop he fetch first 1k rows and delete them from memory, takes next 1k rows and so on. If we know how to split the data then we can use more than one `cursor` to fetch the data.

**Comment by michalz92** [comment]
** Split the data into several files to utilize Redshift's built-in parallelization**
As per today's call, we don't want to use Redshift's parallelization, but instead upload big files with multiple single-file uploads that will be easier to re-run in case of failure of any of the parts.

**Comment by michalz92** [comment]
To sum up, we only need to add file compression to make the process relatively well optimized for our current use cases.

**Comment by michalz92** [comment]
I think proved to be fast enough that we don't have to worry for now.
