### ISSUE TITLE
remove pendulum from dependencies

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#168]

**Comment by acivitillo** [comment]
Is this done?

**Comment by acivitillo** [comment]
is this done @michalz92 ?

**Comment by michalz92** [comment]
Done, although we will probably want to go back to it since it's much cleaner than the builtin datetime (builtin is not timezone-aware by default, and some operations only work on datetimes without timezone info). I think the ideal is to have timezone-aware UTC datetimes everywhere. Not sure where we could use it right now, but it's definitely a best practice and it's very easy to do with pendulum.
