### ISSUE TITLE
qf.union() missing 'auto config by name'

### ISSUE THREAD

**Issue by vperluzzo** [kfk/grizly#169]
In Alteryx, we have the option to make unions either by name or by position. Then also the option to keep all output fields or just the common ones. 
![image](https://user-images.githubusercontent.com/51827647/67396466-ef05f780-f5a7-11e9-8852-14fdc53e30a2.png)

Right now in union() we have only `auto config by position`, then we choose `union_type="UNION' `or `"UNION ALL"`. **This means Piotr and I are checking each of the subqueries, selecting/deselecting/rearranging...** which is a pain. 

Can we add a union_by argument ("POSITION"/"NAME"), then the union_type changed to "COMMON"/"ALL"

@malinaa96 

_Please?_

**Comment by malinaa96** [comment]
The thing is that the QFrame is used to build a query and for what I now we can't just add something to the query so that it unions by the name of the columns. As it's mentioned [here](https://www.w3schools.com/sql/sql_union.asp) 
![image](https://user-images.githubusercontent.com/52569986/67663888-c2b2f800-f966-11e9-9b64-89bb04c84b14.png)

The only solution that I see is to check what are the names of the columns in the first QFrame and use rearrange method on the second QFrame so that the order is the same. 

Let me know if this one is urgent, cause this would also require some tests - I'm not sure if this is the best solution.

**Comment by malinaa96** [comment]
`union_by` added and tested in 0.3, we agreed that we won't change argument default values

**Comment by bing9** [comment]
Hi @malinaa96 ,

Question regarding this: is the column on both side auto-complete? I see you have implemented union_by : {'position', 'name'}, however, the second requirement from @vperluzzo to auto-complete by {'common', 'all'} fields are not implemented?
-> Would we have auto-complete? Please?

> Right now in union() we have only auto config by position, then we choose union_type="UNION' or "UNION ALL". This means Piotr and I are checking each of the subqueries, selecting/deselecting/rearranging... which is a pain.
> 
> Can we add a union_by argument ("POSITION"/"NAME"), then the union_type changed to "COMMON"/"ALL"

I have checked **0.3** release. still below using assert both query has same alias.

```
            assert field_diff_1 == set() and field_diff_2 == set(), f"""Aliases {field_diff_2} not found in 1. QFrame, aliases {field_diff_1} not found in {iterator}. QFrame. Use qf.rename() to rename fields or set option union_by='position'"""
            ordered_fields = []
```

Regards,

Bing

**Comment by malinaa96** [comment]
Hi @bing9!

Yes, for now we don't have any auto-complete in the union - the only improvement is `union_by` option (https://grizly-docs.readthedocs.io/en/0.3/content/api/tutorial_qframe_new.html#Unioning-data). We can think about auto-complete in the next release.

Best,
Kasia
