### ISSUE TITLE
Email function with attachment files

### ISSUE THREAD

**Issue by bing9** [kfk/grizly#222]
Hi team,

It would be really helpful if we could add one or more attachments in the email function.

Thank you!

Bing @Trymzet

**Comment by michalz92** [comment]
Added with #224. @acivitillo can we merge into master?

**Comment by michalz92** [comment]
Note I've only added support for a single attachment for now, so for now use 7z or similar if you have more than one file.

**Comment by acivitillo** [comment]
Since attachments are not mandatory not sure if we want to put this in __init__(). To me it would be better to have an add_attachment() method. This way it is also more obvious adding more than 1 attachment.

```python
email = Email(to, subject, etc.)
email.add_attachment()
email.send()
```

We probably also want a to_body() method eventually to add stuff to the body like screenshots.

**Comment by michalz92** [comment]
Well from the protocol perspective, you only need the sender and the recipient, so subject and body shouldn't really be required either and should default to empty. I don't see why attachment should be singled out.

Adding images to the body requires a separate function because the image has to be converted to bytes. I'd say if you want to manipulate the body, then do it when defining your body variable, or work on email.body if you're reusing another email. Embedding images would be an exception because the user can't simply provide a link to the file in the HTML the normal way -- unless we want to parse the <img src> inside HTML under the hood, which is also a possibility. A bit more code, but intuitive for the user.

**Comment by michalz92** [comment]
Closing this as functionality has been added. Let's discuss internally the API structure.
