### ISSUE TITLE
Consider S3 -> AWS Glue -> Redshift Spectrum stack

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#269]
Probably connected with Extract class...

With this approach, we store all data on S3 and only process it with Redshift. To make this work, we need metadata for S3 files (e.g. data types), which can be handled using AWS Glue. Basically the end result is you can query Redshift as you would normally, but the data is stored on S3.

I've read about Athena over the weekend, but honestly Redshift Spectrum seems like a better option for us, since we already have Redhsift clusters set up. Check out https://blog.openbridge.com/how-is-aws-redshift-spectrum-different-than-aws-athena-9baa2566034b for quick comparison. See https://docs.aws.amazon.com/redshift/latest/dg/c-getting-started-using-spectrum.html for a quick overview. https://www.linkedin.com/pulse/aws-spectrum-sql-queries-made-simple-glue-chakri-botlaguduru/ for an actual tutorial.

Whichever method we choose, we need metadata for S3 files (I think for us it just means data types), which can be handled with AWS Glue: https://aws.amazon.com/blogs/big-data/build-a-data-lake-foundation-with-aws-glue-and-amazon-s3.

![alt text](https://d1.awsstatic.com/Products/product-name/diagrams/product-page-diagram_Glue_Unified-View-of-Data-Across-Multiple-Data-Stores.0aa670c04b8b8f68f36fb2f6916cd0bf1b12f43a.png)

**Comment by acivitillo** [comment]
@michalz92 which release would this be and is it grizly or acoe work?

**Comment by itsmygithub123** [comment]
I read the comments from Michal and it makes sense to consider Redshift Spectrum over Athena since you already have a Redshift Cluster. The objects in S3 needs to be crawled to create a metadata layer in Glue that would be used by RS Spectrum to query. Please note the Redshift Spectrum needs a Redshift Cluster but Athena is completely serverless. I would think any exploratory querying can be done through Athena but for end user consumption Spectrum might be a better option. The costing on Athena is $5 for every TB of Scan and for spectrum its the same in addition to the Redshift Cluster cost. Tableau and Power BI have connectors to Redshift Spectrum. The data in S3 would have to partitioned and organized optimally to reduce your scan cost.

**Comment by acivitillo** [comment]
OK guys are we able to do this in a simple way? I am thinking we can move from CSV to Parquet format and Parquet has data types. Would it be possible to have a crawler that automatically catalogues data in S3 in Parquet format? This way we wouldn't have to get to deep into glue.

**Comment by michalz92** [comment]
I don't think it's simple to deploy. But it looks relatively simple to manage.

I think the crawlers can automatically detect most data types. Not sure if this means we can rely on them or if we still need to manually define some stuff.

**Comment by acivitillo** [comment]
@SubashRanganathan are you able to give us a roadmap to implement spectrum?

**Comment by michalz92** [comment]
Looks like we're implementing Spectrum (and possibly Glue), so I'm closing this.
