### ISSUE TITLE
Installing 0.3 Bug -> no assert on package simple_salesforce / exchangelib/ croniter

### ISSUE THREAD

**Issue by bing9** [kfk/grizly#359]
Hi team,

When installing 0.3 , I do not get all dependencies installed. Once import grizly, I have to separately install 3 more packages mannually: simple_salesforce / exchangelib/ croniter

Regards,

Bing

**Comment by malinaa96** [comment]
Hi!

These libraries are in the [requirements.txt](https://github.com/kfk/grizly/blob/0.3/requirements.txt) file so they should be installed together with grizly but maybe you got some connection errors during installation? This may be caused by the proxy. Do you have HTTPS_PROXY specified in environment variables? 
The other solution would be to install the requirements directly from file, so in CMD you do
```cd grizly```
```pip install -r requirements.txt```

Br,
Kasia

**Comment by bing9** [comment]
Thank you so much Kasia!
