### ISSUE TITLE
to_rds() with parquet files

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#381]
We had a bug with `null` columns and `double`. Those columns where not mapped in `pyarrow_to_rds_type()`, now they are in grizly 0.4.

But we need to find a better way to deal with string. Doing `VARCHAR(500)`  for all string is not a good idea and it might break with strings >500.

**Comment by malinaa96** [comment]
As I wrote in https://github.com/kfk/grizly/issues/376 I don't know the full list of `pyarrow` types so that's good that you add it, we will probably have more of them. I wouldn't set 
`"null": "FLOAT8"`

because if we have only nulls in the column then we really have no idea what is the type that's why I think it should be 
`"null": "VARCHAR(500)"`

which is much safer. Can we change it?

**Comment by acivitillo** [comment]
Do we have an idea and can we close this?

**Comment by malinaa96** [comment]
yes but still, can we set `"null": "VARCHAR(500)"` ?

**Comment by malinaa96** [comment]
Ok I changed it just in case if we get any errors in the future.
