### ISSUE TITLE
qframe groupby should create a select subquery

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#428]
Right now groupby just adds "Group By" clause but it does not change the "Select". This means for a proper group by you need to run `qf.select()` first. I think this is a bit misleading and I would have `qf.groupby()` to automatically also do a `qf.select()`.

@malinaa96 @michalz92 @bing9 @pmarekk @pattrycja96

**Comment by malinaa96** [comment]
So in my opinion this is not a good idea because when you do `QFrame.select(fields)` your QFrame is automatically limited to `fields` so if `QFrame.groupby()` would do select automatically then you won't be able to do any aggregation after. For example 
```python
qf.groupby(['CustomerId'])['Sales'].agg('sum')
```
won't be possible because after grouping the only field that is left is `CustomerId`.

I think we can add an enhancement to `QFrame.groupby()` to automatically group by all the fields. With this solution you can do
```python
qf.select(fields).groupby()
```
instead of
```python
qf.select(fields).groupby(fields_with_sq)
```

You would still have to use both methods but in my opinion it's also more clear how the query looks like.

Guys what do you think?

**Comment by acivitillo** [comment]
I think

```python
qf.select(fields).groupby()
```

makes a lot more sense than my initial proposal. How difficult is to implement? I guess it should be few changes in `groupby()` only.

**Comment by malinaa96** [comment]
It only requires changing `def groupby(self, fields)` to `def groupby(self, fields=None)` and adding
```python
if fields is None:
    fields = self.get_fields()
```

**Comment by acivitillo** [comment]
OK let’s do it then.

**Comment by malinaa96** [comment]
Done
