### ISSUE TITLE
to_excel not working

### ISSUE THREAD

**Issue by PrzemyslawJonczak** [kfk/grizly#464]
this is my code i am writing: 
![image](https://user-images.githubusercontent.com/67792827/86934571-261f3780-c13c-11ea-9a34-d61194571afd.png)
but i am getting the following error 
![image](https://user-images.githubusercontent.com/67792827/86935118-c5442f00-c13c-11ea-9686-0067830d252d.png)

**Comment by malinaa96** [comment]
Hi!

Thanks for the feedback. Yes this is a bug and it's fixed in new version of grizly which will be released this week. If you cannot wait you can also use pandas `DataFrame.to_excel` so you would do

```python
df = qf.to_df()
df.to_excel()
```
although this method works only if you have one sheet in your excel.

Thanks in advance for patience :)

**Comment by malinaa96** [comment]
It should work on 0.3.6 so I'm closing we can reopen if any case of any further issues
