### ISSUE TITLE
to_excel partially works

### ISSUE THREAD

**Issue by PrzemyslawJonczak** [kfk/grizly#475]
Hi, the to_excel function seems to works but there are issues... 
first of all the scenario: template excel file named test_clean.xlsx with the following formatting: 
![image](https://user-images.githubusercontent.com/67792827/87637857-24a8cd00-c743-11ea-8ed1-83c8a628d3d6.png) 
then empty output excel file named testout.xlsx: 
![image](https://user-images.githubusercontent.com/67792827/87637967-4ace6d00-c743-11ea-9c26-a109e3112241.png)
When I execute the code attached 
[to_excel_issue_2.txt](https://github.com/kfk/grizly/files/4929841/to_excel_issue_2.txt)

Pls run the code and see the case. 
The function uses the output file name and tries to use it as the worksheet name. 
The function populates the input file but it overwrites the formatting. 
The function doesn't save the data in the desired output file (only in the input file). 

Let me show the case - Skype or Teams - whatever suits you Kasia...

**Comment by malinaa96** [comment]
Hi !

I noticed that you are still using `Dataframe.to_excel()`  as `QFrame.to_df()` returns a DataFrame

![image](https://user-images.githubusercontent.com/52569986/87643146-c384f780-c74a-11ea-8a43-dd903b081343.png)

You can try to use now `QFrame.to_excel()` directly as I already fixed the bug that was in this method, so you can do  

```python
joined_qf.to_excel("/home/analyst/test_clean.xlsx"
         ,"/home/analyst/testout.xlsx"
         , sheet_name='abc'
         , startrow=0
         , startcol=0
         , index=False
         , header=True
        )
```


The issues that you had with paths was because `DataFrame.to_excel()` doesn't support input and output excel files - they only have one path.

**Comment by PrzemyslawJonczak** [comment]
Hi, switching to the QueryFrame works! 
Just one comment: 
The name of the output worksheet: 
, sheet_name='abc' 
needs to be the same as the name of the worksheet with formatting in the input file.
