### ISSUE TITLE
need to eliminate all local config requirement, should be option only

### ISSUE THREAD

**Issue by kfk** [kfk/grizly#91]
The OS[Environment] or [UserProfile] are Windows specific. We need to rethink the config option and make it optional and not required.

`WARNING: autodoc: failed to import method 'QFrame.to_rds' from module 'grizly'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/grizly-docs/envs/alessio/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grizly-docs/checkouts/alessio/grizly/__init__.py", line 1, in <module>
    from .api import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/grizly-docs/checkouts/alessio/grizly/api.py", line 1, in <module>
    from .core.qframe import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/grizly-docs/checkouts/alessio/grizly/core/qframe.py", line 21, in <module>
    from grizly.io.etl import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/grizly-docs/checkouts/alessio/grizly/io/etl.py", line 8, in <module>
    from grizly.core.utils import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/grizly-docs/checkouts/alessio/grizly/core/utils.py", line 19, in <module>
    os.environ["HTTPS_PROXY"] = config["https"]
TypeError: string indices must be integers
`

**Comment by acivitillo** [comment]
@malinaa96 @pattrycja96 and @michalz92 please have a look to this config structure:

```python
from inspect import getfullargspec

class Config(dict):
    def __init__(self):
        dict.__init__(self)
        
    def from_dict(self, d):
        for key in d:
            self[key] = d[key]

class Pipeline():
    def __init__(self):
        self.config = Config()
        
class Extract(Pipeline):
    def __init__(self, pipeline=None):
        p = Pipeline.__init__(self)
        if pipeline != None:
            self.config = pipeline.config
        else:
            self.config = p.config
    
    def printConf(self, engine_str:str=None):
        args = {}
        if self.config == {}:
            args = locals()
        else:
            for param in locals():
                if param != 'self' and param !='args':
                    args[param] = self.config[param]
        test = 2
        print(args)

class Load(Pipeline):
    def __init__(self, pipeline=None):
        p = Pipeline.__init__(self)
        if pipeline != None:
            self.config = pipeline.config
        else:
            self.config = p.config
    
    def printConf(self, engine_str:str=None):
        args = {}
        if self.config == {}:
            args = locals()
        else:
            for param in locals():
                if param != 'self' and param !='args':
                    args[param] = self.config[param]
        test = 2
        print(args)
        
p = Pipeline()
d = {"engine_str":"some_string"}
p.config.from_dict(d)
Load(p).printConf()

p2 = Pipeline()
d2 = {"engine_str":"some_string_2"}
p2.config.from_dict(d2)
Extract(p2).printConf()
Extract(p).printConf()
```
We create a Pipeline class. Then **all** our classes inherit from Pipeline. Pipeline holds the configurations. We can then also add many more methods to manage pipeline like i.e. get_json representation.

We can the do one of 2 things:

- Configure the class
- Configure the pipeline and inherit the confs in the classes

**Comment by acivitillo** [comment]
And if we use dask.delayed we can do the below. This is even better as we can **register** tasks to a **pipeline** and then compute the entire thing in parallel. This means if you have parallel tasks your workflow will run a lot faster than it would run in Alteryx.

```python
import dask
from inspect import getfullargspec, signature

class Config(dict):
    def __init__(self):
        dict.__init__(self)
        
    def from_dict(self, d):
        for key in d:
            self[key] = d[key]
        return self

class Load():
    def __init__(self, pipeline):
        self.config = pipeline.config
        self.args = {}
    
    @dask.delayed
    def deletethis2(self, text_path:str=None, text:str=None):
        with open(text_path, "w") as tfile:
            tfile.write(text)
        return self

class Pipeline():
    def __init__(self):
        self.config = Config()
        self.pipeline = []
    
    def register_task(self, func):
        self.pipeline.append(func)
        return self
    
    def compute(self):
        output = dask.delayed()(p.pipeline).compute()
        return output
        
p = Pipeline()
d = {"engine_str":"some_stringjj"}
p.config.from_dict(d)
text_file = Load(p).deletethis2("file1.txt", "retest33")
p.register_task(text_file)
text_file = Load(p).deletethis2("file2.txt", "retest22")
p.register_task(text_file)
p.compute()
```

**Comment by michalz92** [comment]
But what does this bring that Workflow doesn't have? To me it looks like rewriting the Workflow class. We can add load_config() as a method to Workflow if needed. Workflow has built-in logging and status reporting, and we can specify task dependencies. Essentially what the workflow owner has to do at this moment is to modify `generate_workflow()`. This is 5-10 lines of code, even at this early stage. Below is a end-user template. I'd say we work from there rather than recreating everything from scratch.

```python
import dask
import os
from grizly import QFrame, read_config

Workflow = __import__("infrastructure.scheduler", fromlist=[None]).Workflow
Schedule = __import__("infrastructure.scheduler", fromlist=[None]).Schedule
load_qf = __import__("infrastructure.scheduler", fromlist=[None]).load_qf
qf_to_csv = __import__("infrastructure.scheduler", fromlist=[None]).qf_to_csv
csv_to_s3 = __import__("infrastructure.scheduler", fromlist=[None]).csv_to_s3
s3_to_rds_dask = __import__("infrastructure.scheduler", fromlist=[None]).s3_to_rds_dask


# edit below variables as required
chunksize = 25000
json_path = os.path.join(r'\infrastructure\data_loads\project_name', 'project_json.json')

schema = "schema"
table = "table"
csv_path = "csv_path"
workflow_name = "Nice workflow name"
owner_email = "owner@te.com"
backup_email = "backup@te.com"


def generate_workflow():
    
    qf = load_qf(path=json_path, subquery="some_subquery")
    
    csv = qf_to_csv(qf, csv_path=csv_path, chunksize=chunksize)
    s3 = csv_to_s3(csv)
    rds = s3_to_rds(qf=qf, s3_status=s3, csv_path=csv_path, schema=schema, table=table, if_exists="append")

    wf = Workflow(name=workflow_name, owner_email=owner_email, backup_email=backup_email, tasks=[rds])
    sched = Schedule("0 5 * * 1") # schedule in cron fromat, here: every Monday at 5 am UTC
    wf.add_schedule(sched)

    return wf
```

**Comment by acivitillo** [comment]
It is the workflow class but it's **embedded** in the analyst workflow. Basically analysts using grizly would be working by adding tasks to a pipeline. Instead right now grizly analysts mostly write scripts to convert to dask.delayed later.

We can definitely repurpose workflow for this and maybe rename it to pipeline. But again, this needs to be come full part of the rest of the grizly functions.

**Comment by michalz92** [comment]
I think for this we can add a `@task` decorator that decorates any function with `@retry` and `@dask.delayed` and also adds an upstream=None keyword, so that task relationships can be specified (e.g. using task.set_upstream(other_task). 

So the analyst writes their functions as usual, decorates with @task, sets dependencies, and adds to Workflow/Pipeline. Pretty much like Prefect, but simpler -- the execution (parallelization, retries, scheduler) and logging is handled "server-side" rather than by the analyst. Finally, they add a schedule with a simple `add_schedule()`.

**Comment by michalz92** [comment]
I should note that `dask.delayed()` figures out dependency by looking at function arguments. E.g. in the template above, in order to tell Dask that `csv_to_s3()` should be executed after `qf_to_csv()`, we have to pass the result of `qf_to_csv()` as an argument to `csv_to_s3`. Definitely the way we do it now is clumsy and we should have something like `Task.set_upstream(other_task)`.

**Comment by acivitillo** [comment]
I get your point but the idea is to make the workflow very apparent to those that do the analysis. 

So you should be able to do

```python
p = Pipeline()
load_csv = Load(p).from_sql()
p.add(load_csv)
```

Then we should be able to do

```python
p.schedule(...)
```

Or

```python
p.at_listen_event(...)
```

So that when we deploy in production all we have to do is:

```python
from someworkflow import p

while true:
 etc.
```

This is the same you are saying, I am just saying it has to be clear and we probably should consider adding dask.delayed to our grizly functions or find a way to make grizly function delayed if the user wants to compute later.

To your point there will always be user defined functions as this is a programming language, in which case we do:

```python
p = Pipeline()

def amazing_user_function():
   pass

p._add(amazing_user_function)
```

I understand that there are dependencies and that dask takes dependencies from the arguments and the functions instantiations. But this is still working so you can do

```python

p = Pipeline()

a = some_function(...)
b = another_function(a)

p._add(b)
```

However, if the user wants to see the intermediate results he can play with multiple pipelines like so

```python

p1 = Pipeline()
p2 = Pipeline()

a = some_function(...)
b = another_function(a)

p1._add(b)
p2._add(a)

p2.compute() <- intermediate result
```

Now we are computing an intermediate result. We do this often in analytics to do all kind of things including checks and validations.

Another thing, of course there can be multiple branches but eventually there should be only 1 workflow with 1 schedule.

**Comment by malinaa96** [comment]
We will work on this in next release

**Comment by michalz92** [comment]
@malinaa96 We've discussed with Alessio that we should move config to S3 and only keep the stuff needed for S3 login in the local file. Eventually we can maybe use environment variables instead of the file for S3 API creds. So basically, `read_config()` should read the config from S3. Let's talk the details through once you're in the office.

**Comment by malinaa96** [comment]
We talked with @acivitillo about the config file and I agree that this is a good idea to put it in S3 but I think that the aws config should be in `.aws` folder. Then instead of doing this
```python
boto3.resource('s3', 
    aws_access_key_id=grizly_config["akey"], 
    aws_secret_access_key=grizly_config["skey"], 
    region_name=grizly_config["region"])
```
any time we want to connect with s3 files we would just do this
```python
boto3.resource('s3')
```
With this solution we don't need `etl_config.py` file any longer and also other people outside our company can download and install grizly. They won't be able to use any function that connects with aws if they don't have an account but they still will be able to use other functions.


@acivitillo if you want to share grizly with others then we should change the configs now, what do you think?

**Comment by acivitillo** [comment]
Yes configs has to go and we move to s3 for the jsons and .aws for the aws connectivity

Sent from my iPhone

On 12. Nov 2019, at 13:01, malinaa96 <notifications@github.com<mailto:notifications@github.com>> wrote:


The following message was sent from an external e-mail address. Be cautious when clicking on links, opening attachments or providing sensitive information.

________________________________

We talked with @acivitillo<https://github.com/acivitillo> about the config file and I agree that this is a good idea to put it in S3 but I think that the aws config should be in .aws folder. Then instead of doing this

boto3.resource('s3',
    aws_access_key_id=grizly_config["akey"],
    aws_secret_access_key=grizly_config["skey"],
    region_name=grizly_config["region"])

any time we want to connect with s3 files we would just do this

boto3.resource('s3')

With this solution we don't need etl_config.py file any longer and also other people outside our company can download and install grizly. They won't be able to use any function that connects with aws if they don't have an account but they still will be able to use other functions.

@acivitillo<https://github.com/acivitillo> if you want to share grizly with others then we should change the configs now, what do you think?

**Comment by malinaa96** [comment]
@acivitillo can you let me know if this structure of config is ok or should I add something?
```
{
  "config": {
    "acoe_standards": {
      "email": {
        "email_address": "",
        "email_password": "",
        "send_as": "acoe_team@te.com"
      },
      "github": {
        "username": "",
        "username_password": ""
      },
      "s3": {
        "s3_key": "",
        "bucket": "acoe-s3",
        "file_dir": "%USERPROFILE%/s3_loads",
        "redshift_str": "mssql+pyodbc://redshift_acoe"
      },
      "sfdc": {
        "stage": {
          "username": "",
          "password": "",
          "instance_url": "cs40-ph2.ph2.r.my.salesforce.com",
          "organizationId": "00DE0000000Hkve"
        },
        "prod": {
          "username": "",
          "password": "",
          "organizationId": "00DE0000000Hkve"
        }
      }
    }
  }
}
```

**Comment by acivitillo** [comment]
Looks good. So we should be able to do stuff like

```python
config_file = S3().from_file(config_key)
store = Store().add_config(config_file)
```

Right?

**Comment by michalz92** [comment]
To me it would be more like this
```python
acoe_config = S3(file_name="acoe_config.json", key="config/").to_clipboard()
store = Store().add_config(acoe_config)
```

What you did above would try to add an S3 object (representing an s3 file) to the store. What we want is the content of that S3 object.

**Comment by acivitillo** [comment]
Well we also have a Config() class so probably we want to do

‘’’python
configs = S3.read_file(key=standard_configs.json)
config = Config().read_json(configs)
Store.add_key(config=config)
‘’’

You can also just use the config object here without adding to the store, this way it always picks the latest configs loaded in s3.

Alessio

Sent from my iPhone

On 19. Nov 2019, at 18:17, Michal Zawadzki <notifications@github.com<mailto:notifications@github.com>> wrote:


The following message was sent from an external e-mail address. Be cautious when clicking on links, opening attachments or providing sensitive information.

________________________________

To me it would be more like this

acoe_config = S3(file_name="acoe_config.json", key="config/").to_clipboard()
store = Store().add_config(acoe_config)

What you did above would try to add an S3 object (representing an s3 file) to the store. What we want is the content of that S3 object.

**Comment by malinaa96** [comment]
And what about the insides of config? Should we only have the credentials there or the default arguments of the classes (like s3_key or s3_bucket) should also be there?

**Comment by acivitillo** [comment]
I think we should run with credentials only for now and then see if we can add some of the defaults later. Step by step.

**Comment by malinaa96** [comment]
So for now we don't need s3 in this config file at all?

**Comment by malinaa96** [comment]
And also I can get read of config argument in AWS (S3) class?

**Comment by malinaa96** [comment]
Ok so this is a new configuration structure:
```
{
  "config": {
    "email": {
      "email_address": "",
      "email_password": "",
      "send_as": ""
    },
    "github": {
      "username": "",
      "username_password": ""
    },
    "sfdc_stage": {
      "username": "",
      "password": "",
      "instance_url": "",
      "organizationId": ""
    },
    "sfdc_prod": {
      "username": "",
      "password": "",
      "organizationId": ""
    }
  }
}
```

Now there is a question, how the default configuration should work? Should we pass the `config` argument to each class and it should be mandatory or maybe we can keep one `config.py` file in `.grizly` which will contain default values and if we don't specify `config` argument then we will read this config?

**Comment by acivitillo** [comment]
.grizly has to go

I think if you set it up as global you can also skip the config in each class

Maybe something like

```python
Config().read_json(json_path, global_config = True)
```

?

**Comment by michalz92** [comment]
But if there is no .grizly, then the open source user has no way to specify a config. We (acoe) can have a .grizly config in which we have a default template from s3, while the open source user will put their own config there.

**Comment by acivitillo** [comment]
@malinaa96 proposed to move the aws credentials to the .aws folders. As per the rest of the configs the open source user can load configs from a local or remote config json

**Comment by malinaa96** [comment]
I checked what is the approach in boto3. For sure the way they do it is very complex as they have several classes for configuration but as I found [here](https://github.com/boto/botocore/blob/develop/botocore/configprovider.py)
![image](https://user-images.githubusercontent.com/52569986/69522212-1feb9a80-0f61-11ea-864a-7f8b7ad55233.png)
you can pass the credentials in four ways. One of the ways that we didn't consider is the environment variables. I'm not saying that we should keep the credentials there but what about having GRIZLY_CONFIG_FILE variable which will keep the path to the folder where config is stored? They use the same approeach in [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html)

![image](https://user-images.githubusercontent.com/52569986/69522641-39d9ad00-0f62-11ea-98a4-4cdc4d8278a1.png)


As you think about it the config file that we have now contain only credentials so it looks the same for every workflow.

**Comment by acivitillo** [comment]
Sounds good to me. So we have a `.aws` folder with the credentials?

**Comment by malinaa96** [comment]
Yes, in this folder we have credentials for aws which we generate using `aws configure` command. Then we will have another config file with other credentials which grizly will look for in GRIZLY_CONFIG_FILE path or if it's not specified we can take a default `'%USERPROFILE%/.grizly`. What do you think?

**Comment by malinaa96** [comment]
@acivitillo @michalz92  I finished Config class - it's not perfect yet but we have something at least. It's on my branch. I didn't push it yet to master because there are a lot changes and I did some tests but still something can go wrong as I had to change parameters. So I want to ask you if you have any free time tomorrow or on Friday please test it on your PC's and let me know if it works as you want it to work. For now I only added it to `Extract` and `Email` classes.

Take a look at this tutorial:
https://github.com/kfk/grizly/blob/kasia/notebooks/config.ipynb

**Comment by acivitillo** [comment]
OK I started to have a look. I have created a new branch 0.3_config based on yours and I will do my changes there over the weekend. I noticed few bugs in Email and Extract so I will clean this up. I will then probably clean up Load and QFrame and play with it a bit to see if it makes sense.

Next step will be to ask Kamil/Patrycja to take a test run with 0.3, this will probably be done in January though. I would focus December on cleaning up Grizly as much as possible and do a release launch with the team mid Jan after beta testing.

**Comment by malinaa96** [comment]
Ok, I'm waiting until you merge to 0.3 so that I can work pull and work on other issues.

**Comment by malinaa96** [comment]
I added proxies key to the config now it looks like
```json
{
  "config": {
    "standard": {
      "email": {
        "email_address": "my_email@example.com",
        "email_password": "my_password",
        "send_as": "Team"
      },
      "github": {
        "username": "my_login",
        "proxies": {
          "http": "first_proxy",
          "https": "second_proxy"
        },
        "pages": 100,
        "username_password": "my_password"
      },
      "sfdc": {
        "stage": {
          "username": "my_login",
          "instance_url": "https://na1.salesforce.com",
          "password": "my_password",
          "organizationId": "OrgId"
        },
        "prod": {
          "username": "my_login",
          "password": "my_password",
          "organizationId": "OrgId"
        }
      },
      "proxies": {
        "http": "first_proxy",
        "https": "second_proxy"
      }
    }
  }
}
```

I will remove `proxies` key from `github` key. I also added `Config.get_service()` method 
https://grizly-docs.readthedocs.io/en/0.3/content/api_Config.html#grizly.Config.get_service
It's useful when you want to get config in other classes. You can check how I use it in `Extract` class
https://github.com/kfk/grizly/blob/0.3/grizly/extract.py
```python
        if None in [username, username_password, pages]:
            config_github = Config().get_service(service='github')

        username = username or config_github['username']
        username_password = username_password or config_github['username_password']
        pages = pages or config_github['pages']
        proxies = proxies or config_github['proxies']
```

**Comment by michalz92** [comment]
I guess we've implemented this now, right?

**Comment by acivitillo** [comment]
I think so, can we close?

**Comment by michalz92** [comment]
I'd say yes, but we should check with Kasia if the Config is still required anywhere.

**Comment by acivitillo** [comment]
@malinaa96 ?

**Comment by malinaa96** [comment]
I'm good we can close it
